// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmb52iFrGoEx3jEdKnQq9orNhEJZgOpvI',
    appId: '1:733591829128:android:1a65763d207f2d86ea7d3d',
    messagingSenderId: '733591829128',
    projectId: 'flutter-learn-app-8805e',
    storageBucket: 'flutter-learn-app-8805e.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXH-PguCE58ovMBOjFIEiAvcBN9frLL7k',
    appId: '1:733591829128:web:d8040368980bfdf5ea7d3d',
    messagingSenderId: '733591829128',
    projectId: 'flutter-learn-app-8805e',
    authDomain: 'flutter-learn-app-8805e.firebaseapp.com',
    storageBucket: 'flutter-learn-app-8805e.firebasestorage.app',
    measurementId: 'G-14ZB09GTN4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDs8YiytPovLhnHacmxMGyrTCs1kX-5AeU',
    appId: '1:733591829128:ios:75fd3507e0bbd2fbea7d3d',
    messagingSenderId: '733591829128',
    projectId: 'flutter-learn-app-8805e',
    storageBucket: 'flutter-learn-app-8805e.firebasestorage.app',
    iosBundleId: 'com.flutterlearnapp.flutterLearnApp',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDs8YiytPovLhnHacmxMGyrTCs1kX-5AeU',
    appId: '1:733591829128:ios:75fd3507e0bbd2fbea7d3d',
    messagingSenderId: '733591829128',
    projectId: 'flutter-learn-app-8805e',
    storageBucket: 'flutter-learn-app-8805e.firebasestorage.app',
    iosBundleId: 'com.flutterlearnapp.flutterLearnApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXH-PguCE58ovMBOjFIEiAvcBN9frLL7k',
    appId: '1:733591829128:web:1eb129d8154d42cbea7d3d',
    messagingSenderId: '733591829128',
    projectId: 'flutter-learn-app-8805e',
    authDomain: 'flutter-learn-app-8805e.firebaseapp.com',
    storageBucket: 'flutter-learn-app-8805e.firebasestorage.app',
    measurementId: 'G-PPP4KV4GSD',
  );

}